name: Python application CI/CD
on:
  push:
    branches: [ main, dev ]  # Branch to survey
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Add any specific installation commands for libcpab
        # pip install -e libcpab


    # tests
    - name: Run unit tests (un fichier)
      run: |
        pytest tests/test_morpion.py
    # - name: Run unit tests (un autre fichier)
    #   run: |
    #     pytest tests/test_1.py

